/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppRedacaoRouteImport } from './routes/_app.redacao'
import { Route as AppPremiumRouteImport } from './routes/_app.premium'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppIaRouteImport } from './routes/_app.ia'
import { Route as AppEstatisticasRouteImport } from './routes/_app.estatisticas'
import { Route as AppCronogramaRouteImport } from './routes/_app.cronograma'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppQuestoesIndexRouteImport } from './routes/_app.questoes.index'
import { Route as AppSessaoIdRouteImport } from './routes/_app.sessao.$id'
import { Route as AppQuestoesIdRouteImport } from './routes/_app.questoes.$id'
import { Route as AppInsightIdRouteImport } from './routes/_app.insight.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRedacaoRoute = AppRedacaoRouteImport.update({
  id: '/redacao',
  path: '/redacao',
  getParentRoute: () => AppRoute,
} as any)
const AppPremiumRoute = AppPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppIaRoute = AppIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AppRoute,
} as any)
const AppEstatisticasRoute = AppEstatisticasRouteImport.update({
  id: '/estatisticas',
  path: '/estatisticas',
  getParentRoute: () => AppRoute,
} as any)
const AppCronogramaRoute = AppCronogramaRouteImport.update({
  id: '/cronograma',
  path: '/cronograma',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestoesIndexRoute = AppQuestoesIndexRouteImport.update({
  id: '/questoes/',
  path: '/questoes/',
  getParentRoute: () => AppRoute,
} as any)
const AppSessaoIdRoute = AppSessaoIdRouteImport.update({
  id: '/sessao/$id',
  path: '/sessao/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestoesIdRoute = AppQuestoesIdRouteImport.update({
  id: '/questoes/$id',
  path: '/questoes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightIdRoute = AppInsightIdRouteImport.update({
  id: '/insight/$id',
  path: '/insight/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/cronograma': typeof AppCronogramaRoute
  '/estatisticas': typeof AppEstatisticasRoute
  '/ia': typeof AppIaRoute
  '/perfil': typeof AppPerfilRoute
  '/premium': typeof AppPremiumRoute
  '/redacao': typeof AppRedacaoRoute
  '/insight/$id': typeof AppInsightIdRoute
  '/questoes/$id': typeof AppQuestoesIdRoute
  '/sessao/$id': typeof AppSessaoIdRoute
  '/questoes/': typeof AppQuestoesIndexRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/cronograma': typeof AppCronogramaRoute
  '/estatisticas': typeof AppEstatisticasRoute
  '/ia': typeof AppIaRoute
  '/perfil': typeof AppPerfilRoute
  '/premium': typeof AppPremiumRoute
  '/redacao': typeof AppRedacaoRoute
  '/': typeof AppIndexRoute
  '/insight/$id': typeof AppInsightIdRoute
  '/questoes/$id': typeof AppQuestoesIdRoute
  '/sessao/$id': typeof AppSessaoIdRoute
  '/questoes': typeof AppQuestoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/cronograma': typeof AppCronogramaRoute
  '/_app/estatisticas': typeof AppEstatisticasRoute
  '/_app/ia': typeof AppIaRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/premium': typeof AppPremiumRoute
  '/_app/redacao': typeof AppRedacaoRoute
  '/_app/': typeof AppIndexRoute
  '/_app/insight/$id': typeof AppInsightIdRoute
  '/_app/questoes/$id': typeof AppQuestoesIdRoute
  '/_app/sessao/$id': typeof AppSessaoIdRoute
  '/_app/questoes/': typeof AppQuestoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/sitemap.xml'
    | '/configuracoes'
    | '/cronograma'
    | '/estatisticas'
    | '/ia'
    | '/perfil'
    | '/premium'
    | '/redacao'
    | '/insight/$id'
    | '/questoes/$id'
    | '/sessao/$id'
    | '/questoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/sitemap.xml'
    | '/configuracoes'
    | '/cronograma'
    | '/estatisticas'
    | '/ia'
    | '/perfil'
    | '/premium'
    | '/redacao'
    | '/'
    | '/insight/$id'
    | '/questoes/$id'
    | '/sessao/$id'
    | '/questoes'
  id:
    | '__root__'
    | '/_app'
    | '/onboarding'
    | '/sitemap.xml'
    | '/_app/configuracoes'
    | '/_app/cronograma'
    | '/_app/estatisticas'
    | '/_app/ia'
    | '/_app/perfil'
    | '/_app/premium'
    | '/_app/redacao'
    | '/_app/'
    | '/_app/insight/$id'
    | '/_app/questoes/$id'
    | '/_app/sessao/$id'
    | '/_app/questoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/redacao': {
      id: '/_app/redacao'
      path: '/redacao'
      fullPath: '/redacao'
      preLoaderRoute: typeof AppRedacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/premium': {
      id: '/_app/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AppPremiumRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ia': {
      id: '/_app/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof AppIaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estatisticas': {
      id: '/_app/estatisticas'
      path: '/estatisticas'
      fullPath: '/estatisticas'
      preLoaderRoute: typeof AppEstatisticasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cronograma': {
      id: '/_app/cronograma'
      path: '/cronograma'
      fullPath: '/cronograma'
      preLoaderRoute: typeof AppCronogramaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/questoes/': {
      id: '/_app/questoes/'
      path: '/questoes'
      fullPath: '/questoes/'
      preLoaderRoute: typeof AppQuestoesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessao/$id': {
      id: '/_app/sessao/$id'
      path: '/sessao/$id'
      fullPath: '/sessao/$id'
      preLoaderRoute: typeof AppSessaoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/questoes/$id': {
      id: '/_app/questoes/$id'
      path: '/questoes/$id'
      fullPath: '/questoes/$id'
      preLoaderRoute: typeof AppQuestoesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insight/$id': {
      id: '/_app/insight/$id'
      path: '/insight/$id'
      fullPath: '/insight/$id'
      preLoaderRoute: typeof AppInsightIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppCronogramaRoute: typeof AppCronogramaRoute
  AppEstatisticasRoute: typeof AppEstatisticasRoute
  AppIaRoute: typeof AppIaRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppPremiumRoute: typeof AppPremiumRoute
  AppRedacaoRoute: typeof AppRedacaoRoute
  AppIndexRoute: typeof AppIndexRoute
  AppInsightIdRoute: typeof AppInsightIdRoute
  AppQuestoesIdRoute: typeof AppQuestoesIdRoute
  AppSessaoIdRoute: typeof AppSessaoIdRoute
  AppQuestoesIndexRoute: typeof AppQuestoesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppCronogramaRoute: AppCronogramaRoute,
  AppEstatisticasRoute: AppEstatisticasRoute,
  AppIaRoute: AppIaRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppPremiumRoute: AppPremiumRoute,
  AppRedacaoRoute: AppRedacaoRoute,
  AppIndexRoute: AppIndexRoute,
  AppInsightIdRoute: AppInsightIdRoute,
  AppQuestoesIdRoute: AppQuestoesIdRoute,
  AppSessaoIdRoute: AppSessaoIdRoute,
  AppQuestoesIndexRoute: AppQuestoesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
